name: dbt Measles Refresh (dev)

on:
  workflow_dispatch: # run manually desde Actions
  schedule:
    - cron: "0 4 1 */3 *" # 1st of every month at 04:00 UTC (ajustable o eliminar si no quieres auto)

jobs:
  dbt-refresh-dev:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}/vaccine_measles_dbt

      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
      SNOWFLAKE_PRIVATE_KEY_B64: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Write Snowflake private key file
        working-directory: ./vaccine_measles_dbt
        run: |
          echo "$SNOWFLAKE_PRIVATE_KEY_B64" | base64 -d > snowflake_key.p8
          chmod 600 snowflake_key.p8

      - name: Install dbt-snowflake
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core==1.8.0" "dbt-snowflake==1.8.0"

      - name: dbt deps
        working-directory: ./vaccine_measles_dbt
        run: dbt deps --profiles-dir .

      - name: Load RAW from S3 (dev)
        working-directory: ./vaccine_measles_dbt
        run: dbt run-operation load_measles_raw_from_s3 --profiles-dir . --target dev

      - name: dbt run (dev)
        working-directory: ./vaccine_measles_dbt
        run: dbt run --profiles-dir . --select stg_measles_* fact_measles_* mart_measles_* --target dev

      - name: dbt test (dev)
        working-directory: ./vaccine_measles_dbt
        run: dbt test --profiles-dir . --select stg_measles_* fact_measles_* mart_measles_* --target dev
